name: base_template
description: Base Template for Riverpod
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_riverpod: ^2.1.1
  flutter_screenutil: ^5.6.0
  freezed: ^2.1.1
  go_router: ^4.5.1
  google_fonts: ^3.0.1
  
dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen: ^5.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true # En
flutter:
  uses-material-design: true
